# Welcome to Jekyll!
#

# Site settings
title: Harry Bradrocco
description: |
  Engineer | |  Photographer | |  
  
 
owner: Harry Bradrocco # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: harrybradrocco@gmail.com 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<harrybradrocco>
  github: https://github.com/<harrybradrocco>
  linkedin-square: https://linkedin.com/in/<harrybradrocco>
  facebook-official: https://facebook.com/<harrybradroccophotography>
   #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:/harrybradrocco
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
